FROM node:20-slim

WORKDIR /app

RUN echo 'const http = require("http"); const server = http.createServer((req, res) => { res.writeHead(200); res.end("OK"); }); server.listen(8080, () => console.log("Server running on 8080"));' > app.js

CMD ["node", "app.js"]
