export const LABELS = {
  tabs: {
    home: "홈",
    search: "업체찾기",
    quotes: "받은견적",
    chats: "채팅",
    profile: "내정보",
  },
  headers: {
    home: "모두의집",
    search: "업체찾기",
    quotes: "받은견적",
    requestDetail: "요청 상세",
    chats: "채팅",
    profile: "내정보",
    login: "로그인",
  },
  actions: {
    back: "뒤로",
    newRequest: "견적 요청하기",
    chat: "채팅",
    select: "선택",
    selecting: "선택중...",
    send: "전송",
    login: "로그인",
  },
  status: {
    open: "열림",
    closed: "마감",
  },
  messages: {
    loading: "불러오는 중...",
    loginRequired: "로그인이 필요합니다.",
    requestNotFound: "요청을 찾을 수 없습니다.",
    noRequests: "열린 요청이 없습니다.",
    noQuotes: "아직 도착한 견적이 없습니다.",
    noChats: "채팅이 없습니다.",
    errorLoadRequests: "요청을 불러오지 못했습니다.",
    errorLoadRequest: "요청을 불러오지 못했습니다.",
    errorLoadQuotes: "견적을 불러오지 못했습니다.",
    errorLoadChats: "채팅을 불러오지 못했습니다.",
    errorOpenChat: "채팅을 열 수 없습니다.",
    noMessages: "메시지가 없습니다.",
    justNow: "방금",
    closedHidden: "마감된 요청은 목록에서 숨김 처리됩니다.",
  },
  labels: {
    budget: "예산",
    status: "상태",
    price: "가격",
    memo: "메모",
    partner: "업체",
    request: "요청",
    quotes: "견적",
    trust: "신뢰",
  },
} as const;
