export const LABELS = {
  tabs: {
    home: "홈",
    requests: "요청",
    quotes: "견적",
    chats: "채팅",
    profile: "내정보",
  },
  headers: {
    home: "요청 목록",
    requests: "요청",
    quotes: "견적",
    requestDetail: "요청 상세",
    chats: "채팅",
    profile: "내정보",
    photos: "업체 사진",
  },
  actions: {
    back: "뒤로",
    chat: "채팅",
    submit: "제출",
    submitting: "제출중...",
    send: "전송",
    addPhotos: "사진 추가",
    delete: "삭제",
    setPrimary: "대표사진",
    retry: "재시도",
  },
  status: {
    open: "열림",
    closed: "마감",
  },
  messages: {
    loading: "불러오는 중...",
    loginRequired: "로그인이 필요합니다.",
    requestNotFound: "요청을 찾을 수 없습니다.",
    noRequests: "요청이 없습니다.",
    noChats: "채팅이 없습니다.",
    errorLoadRequests: "요청을 불러오지 못했습니다.",
    errorLoadRequest: "요청을 불러오지 못했습니다.",
    errorLoadQuotes: "견적을 불러오지 못했습니다.",
    errorLoadChats: "채팅을 불러오지 못했습니다.",
    errorOpenChat: "채팅을 열 수 없습니다.",
    noMessages: "메시지가 없습니다.",
    justNow: "방금",
    closedHidden: "마감된 요청은 신규 견적에서 숨김 처리됩니다.",
    closedVisible: "이미 제출한 견적은 마감 후에도 계속 표시됩니다.",
  },
  labels: {
    budget: "예산",
    status: "상태",
    price: "가격",
    memo: "메모",
    quotes: "견적",
    myQuote: "내 견적",
  },
} as const;
